#!/bin/bash
usage() {
	echo "Usage: $0 FILE [DEST_DIR]"
	exit -1
}
if [ $# -eq 0 ] ; then
	usage
fi

if [[ -f $1 ]]; then
	fd=`readlink -f $1`
else
	echo "Error: $1 is not regular filename."
	usage
fi

dest=`dirname $fd`

if [ [$# -ge 2 ] && [ -f $1 ] && [ -d $2] ] ; then
	dest=$2
else
	echo "Error: $1 is not regular filename. Or $2 isn't a directory."
	usage
fi

cp -v $1 $dest/`basename $1`.`date +%s`

