#!/bin/bash
usage () {
	echo "usage: $0 -[t|g] -s SEARCH_STRING
	-t	search in TranslationProject
	-g	search in GNOME"

	exit -1
}
while getopts "tghs:" opt; do
  case $opt in
    d)
      dir='/mnt/E/TranslationProject'
      ;;
    g)
      dir='/mnt/E/MyProjects/GNOME/*/po/'
      ;;
    s)
	  s=$OPTARG
      ;;
    h|*)
	usage
      ;;
  esac
done

if [[ "$#" -lt "1" ]]; then
	usage
fi
for po in $(find $dir -name *vi.po); do
	msggrep -K -e "$s" $po
done

