#!/bin/bash

wz() {
	git clone "git://git.gnome.org/$1"
	cd $1
	git remote set-url origin "ssh://git.gnome.org/git/$1";
	git remote add git git://git.gnome.org/$1 && git fetch git
	cd po
	gnome -t $1
	exit;
}

usage() {
	echo "usage:
	$0 OPTION
	OPTION is:
	-f	browser Debian sid package
	-b	report bug
	-t	download and merge pot file from master branch
	-s	download and merge pot file from stable branch
	-p	download po file from master branch
	-i	browser git repo on git.debian.org
	-g	add 'git' repo using git:// protocol
	-G	browser GNOME directory in Nautilus
	-T	translate vi.po with gTranslator
	-u	browser on github.com
	-U	merge vi.po with POT file at the same directory
	-w	wizard
	-W	go to Wiki of package
	-m	go to module page
	-H	go to Homepage
	-h	help

Project infomations:

# Copyright © $(date +%Y) GNOME i18n Project for Vietnamese.
# This file is distributed under the same license as the PACKAGE package.
Nhóm dịch GNOME <gnome-vi-list@gnome.org>

Git:
 * git://git.gnome.org/PACKAGE
 * ssh://git.gnome.org/git/PACKAGE
"
	exit;
}

# define stable branch
stable='gnome-3-16'
projectdir='/mnt/E/MyProjects/GNOME'

# get parent dir
getdir () {
# cd ../
# parent=$(basename `pwd`)
# cd -

	pushd $(pwd)
	cd ../
	parent=$(basename `pwd`)
	popd
}

if [[ "$#" -lt "1" ]]; then
	usage
fi

while getopts "f:b:t:Ts:p:i:g:Gu:Uw:W:m:hH" opt; do
  case $opt in
    f)
      /usr/bin/x-www-browser https://packages.debian.org/sid/$OPTARG
      ;;
    t)
      rm -v *.pot *~
      wget --timestamping https://l10n.gnome.org/POT/$OPTARG.master/$OPTARG.master.pot
      msgmerge --verbose --update vi.po $OPTARG.master.pot
      ;;
    s)
      wget --timestamping https://l10n.gnome.org/POT/$OPTARG.$stable/$OPTARG.$stable.pot
      msgmerge --verbose --update vi.po $OPTARG.$stable.pot
      ;;
    p)
      wget --timestamping https://l10n.gnome.org/POT/$OPTARG.master/$OPTARG.master.vi.po
      ;;
    b)
      /usr/bin/x-www-browser https://bugzilla.gnome.org/enter_bug.cgi?product=$OPTARG
      ;;
    i)
      /usr/bin/x-www-browser https://git.gnome.org/browse/$OPTARG/
      ;;
    g)
      git remote add git git://git.gnome.org/$OPTARG && git fetch git
    ;;
    G)
      nautilus $projectdir &
      ;;
    T)
      if [[ -f vi.po ]]; then
      	gtranslator vi.po &
      else
      	gtranslator *.vi.po &
      fi
      ;;
    u)
      /usr/bin/x-www-browser https://github.com/GNOME/$OPTARG/
      ;;
    U)
      if [[ -f vi.po ]]; then
      	msgmerge --verbose --update vi.po *.pot
      else
      	msgmerge --verbose --update *vi.po *.pot
      fi
      ;;
    w)
      wz $OPTARG
      ;;
    W)
      /usr/bin/x-www-browser https://wiki.gnome.org/Apps/$OPTARG
      ;;
    m)
      /usr/bin/x-www-browser https://l10n.gnome.org/module/$OPTARG
      ;;
    H)
	  /usr/bin/x-www-browser https://l10n.gnome.org/teams/vi/
      ;;
    h|*)
	usage
      ;;
  esac
done

