#!/bin/bash
usage() {
	echo "Make FILE become hidden by append ."
	echo "Usage: $0 FILE"
	exit -1
}
if [ $# -eq 0 ] ; then
	usage
fi

if [[ -f $1 ]]; then
	fd=`readlink -f $1`
else
	echo "Error: $1 is not regular filename."
	usage
fi

dest=`dirname $fd`

mv -v $1 $dest/.`basename $1`
