#!/bin/bash

usage() {
	echo "This is a notes manager
	usage: $0 OPTION
	OPTION is:
	-l	list all notes
	-v	view notes
	-e	edit note
	-b  backup
	-h	help"
	exit;
}

if [[ "$#" -lt "1" ]]; then
	usage
fi
configdir=~/.notes
if [[ ! -d "$configdir" ]]; then
	mkdir -v $configdir
fi

while getopts "lv:e:bh" opt; do
  case $opt in
    l)
      ls $configdir
      exit;
      ;;
    v)
      more $configdir/$OPTARG
      exit;
      ;;
    e)
      nano $configdir/$OPTARG
      exit;
      ;;
    b)
      tar -cjvf notes-$(date +%F).tar.bz2 $configdir
      exit;
      ;;
    h|*)
	usage
      ;;
  esac
done

