#!/bin/bash
dir='/usr/share/locale/vi/LC_MESSAGES'
umask 0022
usage (){
	echo $0 [[domain] [file.po]]
	exit
}

[[ -f "vi.po" ]] && po='vi.po' || po=$(ls *vi.po)

case "$#" in
	0 )  if [[ $(basename `pwd`) != "po" ]]; then pkgname=$(basename `pwd`); else usage; fi;;
	1 )  pkgname=$1;;
	2 )  pkgname=$1; po=$2;;
	* )  usage;;
esac
mo=$dir/$pkgname.mo
msgattrib --translated $po > t.t
msgattrib --obsolete $po > t.o
msgcat t.t t.o > t.po
msgfmt --statistics --verbose --check -o $mo t.po
rm -v t.t t.o t.po

