#!/bin/bash
mode='n'
usage() {
	echo "usage: $0 [OPTION] [-m MODE] -f FILENAME
  OPTIONS is:
    -i indent
    -h help
  MODE are:
    a replace all
    n new"
	exit;
}

if [ "$#" -lt "1" ]; then usage
fi

while getopts "im:f:h" opt; do
  case $opt in
    m)
      mode="$OPTARG"
      ;;
    i)
      i="--indent"
      ;;
    f)
      f="$OPTARG"
      ;;
    h|*)
	usage
      ;;
  esac
done

des=$f.po
seddir=/usr/share/doc/myutils/xrp

case $mode in
	a)
		msgfilter $i --input=$f --output-file=$des sed -f $seddir/QUOTES.old
		diff $des $f
		;;
	n)
		msgfilter $i --input=$f --output-file=$des sed  -f $seddir/QUOTES.new
		diff $des $f
		;;
esac

